title: Brenno Ferreira
author: FrBrenno
subtitle: Side-projects & some other things

url: ""
baseurl: ""

highlighter: rouge

footer_only_homepage: true
footer_url: "https://github.com/FrBrenno"
footer_text: "Check my Github"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: ""
